spring.application.name=proyectoClaveCompas

# Configuración de la fuente de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin

# Dialecto de H2 para Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuración de Hibernate para crear/actualizar el esquema
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true


# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

