spring:
  main:
    allow-circular-references: true
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        cache:
          use_second_level_cache: false
          use_query_cache: false
  application:
    name: clavecompas
  datasource:
    jdbcUrl : jdbc:postgresql://localhost:5432/clavecompas
    username: compas
    password: clave
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: clavecompas
  mail:
    host: smtp.gmail.com
    port: 587
    username: clavecompas@gmail.com
    password: wljn qbno zqqo qvpk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: file:src/main/resources/static/
  servlet:
    multipart:
      max-file-size:  10MB
      enabled:  true
      max-request-size: 20MB
server:
  port: 8080
  servlet:
    context-path: /clavecompas
  address: 0.0.0.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs
  paths-to-match: /**
  server:
    url: https://clavecompas-production.up.railway.app

jwt:
  secret: cJYXubdDGdxWUUALFXUNiZeNAuG3+ufM/QhNAk1DE2U=
  access:
    token:
      expiration: 864000000
  refresh:
    token:
      expiration: 2592000000

# Configuración para Cloudinary
cloudinary:
  cloud-name: dlj6zjtpp
  api-key: 698114318994344
  api-secret: QFy9IL3wcGVusDiAo6HSgnrf8PM
  upload-folder: clavecompas
  upload-allowed-formats: jpg,jpeg,png,gif
  upload-max-image-size: 5242880
  #notification-url: ${CLOUDINARY_NOTIFICATION_URL:}

app:
 frontend:
   url: http://localhost:5173