

spring:
  application:
    name: clavecompas
  datasource:
    jdbcUrl : ${DATASOURCE_URL} #jdbc:postgresql://localhost:5432/clavecompas
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
server:
  port: ${SERVICE_PORT}
  servlet:
    context-path: /clavecompas







